-- MySQL Script generated by MySQL Workbench
-- Sun 17 Feb 2019 06:54:06 PM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pipedrive
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pipedrive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pipedrive` ;
USE `pipedrive` ;

-- -----------------------------------------------------
-- Table `pipedrive`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipedrive`.`organization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipedrive`.`organizations_relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipedrive`.`organizations_relationship` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organization_id` VARCHAR(45) NOT NULL,
  `linked_organization_id` VARCHAR(45) NOT NULL,
  `relationship_type` ENUM("parent", "daughter", "sister") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
