version: '2'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pipedrive
    volumes:
      - .:/docker-entrypoint-initdb.d
    #logging:
      #driver: none

  server:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: pipedrive
