FROM node:alpine

RUN apk update && apk upgrade && apk add bash

RUN mkdir -p /app
WORKDIR /app

ADD package.json package-lock.json /app/
RUN npm i

CMD ./scripts/wait-for-it.sh mysql:3306 -- npm run dev
